### ISSUE TITLE
TbcSessionProxy fault with ruby 2.3.4

### ISSUE THREAD

**Issue by meox** [extendi/sunspot#19]
Failures:
```
  1) Sunspot::SessionProxy::TbcSessionProxy all sessions for this configuration
     Failure/Error: project_sessions = @proxy.solr.collections.select { |c| c.start_with?(@base_name) }
     
     NoMethodError:
       private method `select' called for #<String:0x000000050d9878>
     # ./spec/tbc_proxy_spec.rb:251:in `block (2 levels) in <top (required)>'
  2) Sunspot::SessionProxy::TbcSessionProxy simple indexing on wrong object
     Failure/Error: Sunspot.remove_all!
     
     TypeError:
       no implicit conversion of Array into String
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/fault_policy.rb:18:in `+'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/fault_policy.rb:18:in `take_hostname'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:392:in `gen_session'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:101:in `block in all_sessions'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:100:in `each'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:100:in `all_sessions'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:221:in `block in remove_all'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/fault_policy.rb:60:in `with_exception_handling'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:221:in `remove_all'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot/session_proxy/tbc_session_proxy.rb:228:in `remove_all!'
     # /home/travis/build/extendi/sunspot/sunspot/lib/sunspot.rb:515:in `remove_all!'
     # ./spec/spec_helper.rb:26:in `block (2 levels) in <top (required)>'
```
